services:
  api:
    build:
      dockerfile: ../task-list-api/Dockerfile
      context: ../task-list-api
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/task-list
      - spring.datasource.username=test
      - spring.datasource.password=test
    depends_on:
      - database

  database:
    image: postgres:12.19-bullseye

    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: task-list
      TZ: "UTC"
      PGTZ: "UTC"
